    - name: Checkout ammer-core
      uses: actions/checkout@v2
      with:
        path: "ammer-core"

    - name: Compile tests (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        haxelib dev ammer-core ammer-core
        python3-config --cflags
        python3-config --ldflags
        python3-config --libs
        cd ammer-core/test
        haxe -D ammercoretest.python.includepaths="/usr/include/python3.10" -D ammercoretest.python.librarypaths="/usr/lib/python3.10/config-3.10-x86_64-linux-gnu" -D ammercoretest.python.version=10 build/build-python.hxml

    - name: Compile tests (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        haxelib dev ammer-core ammer-core
        python3-config --cflags
        python3-config --ldflags
        python3-config --libs
        cd ammer-core/test
        haxe -D ammercoretest.python.includepaths="/Library/Frameworks/Python.framework/Versions/3.11/include/python3.11;/Library/Frameworks/Python.framework/Versions/3.11/include/python3.11" -D ammercoretest.python.librarypaths=/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/config-3.11-darwin -D ammercoretest.python.version=11 build/build-python.hxml

    - name: Compile tests (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        haxelib dev ammer-core ammer-core
        cd ammer-core/test
        haxe -D ammercoretest.python.includepaths=C:\hostedtoolcache\windows\Python\3.9.13\x64\include -D ammercoretest.python.librarypaths=C:\hostedtoolcache\windows\Python\3.9.13\x64\libs -D ammercoretest.python.version=9 build/build-python.hxml

    - name: Run tests (non-Windows)
      if: matrix.os != 'windows-latest'
      run: |
        cd ammer-core/test
        test/test-python.sh

    - name: Run tests (Windows)
      if: matrix.os == 'windows-latest'
      shell: bash
      run: |
        cd ammer-core/test
        test/test-python-windows.sh
