    - name: Checkout ammer-core
      uses: actions/checkout@v2
      with:
        path: "ammer-core"

    - name: Compile tests (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        haxelib dev ammer-core ammer-core
        source ~/lua5.3/bin/activate
        cd ammer-core/test
        haxe -D ammercoretest.lua.includepaths=`luarocks config --lua-incdir` -D ammercoretest.lua.librarypaths=`luarocks config --lua-libdir` build/build-lua.hxml

    # TODO: the only difference is the `source` call; use leafo's GH actions
    #       for all three systems?
    - name: Compile tests (non-Linux)
      if: matrix.os != 'ubuntu-latest'
      shell: bash
      run: |
        haxelib dev ammer-core ammer-core
        cd ammer-core/test
        haxe -D ammercoretest.lua.includepaths=`luarocks config --lua-incdir` -D ammercoretest.lua.librarypaths=`luarocks config --lua-libdir` build/build-lua.hxml

    - name: Run tests (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        source ~/lua5.3/bin/activate
        cd ammer-core/test
        test/test-lua-linux.sh

    - name: Run tests (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        cd ammer-core/test
        test/test-lua-macos.sh

    - name: Run tests (Windows)
      if: matrix.os == 'windows-latest'
      shell: bash
      run: |
        cd ammer-core/test
        lua bin/lua/test.lua
