    - name: Checkout ammer-core
      uses: actions/checkout@v2
      with:
        path: "ammer-core"

    - name: Compile tests (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        haxelib dev ammer-core ammer-core
        cd ammer-core/test
        haxe build/build-hl.hxml
        haxe build/build-hlc.hxml
        cp $GITHUB_WORKSPACE/hashlink/libhl.so bin/hl
        cp $GITHUB_WORKSPACE/hashlink/libhl.so bin/hlc
        cd bin/hlc
        cc -o main -std=c11 -I. main.c -lhl -L. -lexample

    - name: Compile tests (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        haxelib dev ammer-core ammer-core
        cd ammer-core/test
        haxe build/build-hl.hxml
        haxe build/build-hlc.hxml
        cd bin/hlc
        cc -o main -std=c11 -I. main.c -lhl -L. -lexample

    - name: Compile tests (Windows)
      if: matrix.os == 'windows-latest'
      shell: bash
      run: |
        haxelib dev ammer-core ammer-core
        # https://github.com/ilammy/msvc-dev-cmd#name-conflicts-with-shell-bash
        rm /usr/bin/link
        cd ammer-core/test
        mkdir -p bin/hlc
        cp "$HASHLINK_PATH/libhl.dll" bin/hlc
        cp "$HASHLINK_PATH/libhl.lib" bin/hlc
        haxe -D ammercoretest.hl.includepaths="$HASHLINK_PATH/include" -D ammercoretest.hl.librarypaths="$HASHLINK_PATH" build/build-hl.hxml
        haxe -D ammercoretest.hl.includepaths="$HASHLINK_PATH/include" -D ammercoretest.hl.librarypaths="$HASHLINK_PATH" build/build-hlc.hxml

    - name: Compile tests (MSVC)
      if: matrix.os == 'windows-latest'
      run: |
        cd ammer-core/test/bin/hlc
        cl.exe /Femain.exe /I"$env:HASHLINK_PATH_WIN\include" /I. libhl.lib libexample.lib main.c /link /SUBSYSTEM:CONSOLE /LIBPATH:"."

    - name: Run tests (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        cd ammer-core/test
        test/test-hl-linux.sh
        test/test-hlc-linux.sh

    - name: Run tests (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        cd ammer-core/test
        test/test-hl-macos.sh
        test/test-hlc-macos.sh

    - name: Run tests (Windows)
      if: matrix.os == 'windows-latest'
      shell: bash
      run: |
        cd ammer-core/test
        test/test-hl-windows.sh
        test/test-hlc-windows.sh
