name: Build Windows

on:
  push:
    branches:
      - master
  pull_request:

jobs:
#  test-cpp:
#    runs-on: windows-latest
#    steps:
#    - name: Install Haxe (4.2.5)
#      uses: krdlab/setup-haxe@v1
#      with:
#        haxe-version: 4.2.5
#
#    - name: Checkout ammer-core
#      uses: actions/checkout@v2
#      with:
#        path: "ammer-core"
#
#    - name: Set up haxelibs
#      shell: bash
#      run: |
#        haxelib dev ammer-core ammer-core
#        haxelib git hxcpp https://github.com/HaxeFoundation/hxcpp.git
#        cd `haxelib path hxcpp | head -n 1`
#        cd tools/hxcpp
#        haxe compile.hxml
#
#    - name: Compile tests
#      shell: bash
#      run: |
#        cd ammer-core/test
#        haxe build-cpp-static.hxml
#
#    - name: Run tests
#      shell: bash
#      run: |
#        cd ammer-core/test
#        ./test-cpp-static-windows.sh

  test-hashlink:
    runs-on: windows-latest
    steps:
    - name: Install Haxe (4.2.5)
      uses: krdlab/setup-haxe@v1
      with:
        haxe-version: 4.2.5

    - name: Checkout ammer-core
      uses: actions/checkout@v2
      with:
        path: "ammer-core"

    - name: Set up haxelibs
      shell: bash
      run: |
        haxelib git hashlink https://github.com/HaxeFoundation/hashlink.git master other/haxelib/
        haxelib dev ammer-core ammer-core

    - name: Install HashLink (1.12)
      shell: bash
      run: |
        curl -L https://github.com/HaxeFoundation/hashlink/releases/download/1.12/hl-1.12.0-win.zip -o hashlink.zip
        unzip hashlink.zip
        cd hl-1.12.0-win
        echo "HASHLINK_PATH=`pwd`" >> $GITHUB_ENV
        pwd >> $GITHUB_PATH

    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Compile tests
      shell: bash
      run: |
        cd ammer-core/test
        haxe -D ammercoretest.hl.includepaths="$HASHLINK_PATH/include" -D ammercoretest.hl.librarypaths="$HASHLINK_PATH" build-hl.hxml
        haxe -D ammercoretest.hl.includepaths="$HASHLINK_PATH/include" -D ammercoretest.hl.librarypaths="$HASHLINK_PATH" build-hlc.hxml
        cd bin/hlc
        cl.exe -o main -std=c11 -I$HASHLINK_PATH/include -L$HASHLINK_PATH -I. main.c -lhl -L. -lexample

    - name: Run tests
      shell: bash
      run: |
        cd ammer-core/test
        ./test-hl-windows.sh
        ./test-hlc-windows.sh
