name: Build Linux

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test-cpp:
    runs-on: ubuntu-latest
    steps:
    - name : Adjust path
      run : |
        if [[ -z "$GITHUB_PATH" ]]; then
            echo "${HOME}/.local/bin" >> $GITHUB_PATH
        fi

    - name: Update apt and install necessary packages
      run : |
        if ! command -v sudo &> /dev/null; then
            apt install sudo
        fi
        sudo apt update
        sudo apt-get install -y software-properties-common

    - name: Install Haxe (4.2.5)
      uses: krdlab/setup-haxe@v1
      with:
        haxe-version: 4.2.5

    - name: Checkout ammer-core
      uses: actions/checkout@v2
      with:
        path: "ammer-core"

    - name: Set up haxelibs
      run: |
        haxelib dev ammer-core ammer-core
        haxelib git hxcpp https://github.com/HaxeFoundation/hxcpp.git
        cd `haxelib path hxcpp | head -n 1`
        cd tools/hxcpp
        haxe compile.hxml

    - name: Compile tests
      run: |
        cd ammer-core/test
        haxe build-cpp-static.hxml

    - name: Run tests
      run: |
        cd ammer-core/test
        ./test-cpp-static-linux.sh

  test-hashlink:
    runs-on: ubuntu-latest
    steps:
    - name : Adjust path
      run : |
        if [[ -z "$GITHUB_PATH" ]]; then
            echo "${HOME}/.local/bin" >> $GITHUB_PATH
        fi

    - name: Update apt and install necessary packages
      run : |
        if ! command -v sudo &> /dev/null; then
            apt install sudo
        fi
        sudo apt update
        sudo apt-get install -y software-properties-common

    - name: Install Haxe (4.2.5)
      uses: krdlab/setup-haxe@v1
      with:
        haxe-version: 4.2.5

    - name: Checkout ammer-core
      uses: actions/checkout@v2
      with:
        path: "ammer-core"

    - name: Set up haxelibs
      run: |
        haxelib git hashlink https://github.com/HaxeFoundation/hashlink.git master other/haxelib/
        haxelib dev ammer-core ammer-core

    - name: Checkout HashLink
      uses: actions/checkout@v2
      with:
        repository: "HaxeFoundation/hashlink"
        path: "hashlink"

    - name: Build and install HashLink
      run: |
        cd hashlink
        sudo apt-get install libpng-dev
        sudo apt-get install libturbojpeg-dev
        sudo apt-get install libvorbis-dev
        sudo apt-get install libopenal-dev
        sudo apt-get install libsdl2-dev
        sudo apt-get install libmbedtls-dev
        sudo apt-get install libuv1-dev
        make
        sudo make install

    - name: Compile tests
      run: |
        cd ammer-core/test
        haxe build-hl.hxml
        haxe build-hlc.hxml
        cp $GITHUB_WORKSPACE/hashlink/libhl.so bin/hl/.
        cp $GITHUB_WORKSPACE/hashlink/libhl.so bin/hlc/.
        cd bin/hlc
        cc -o main -std=c11 -I. main.c -lhl -L. -lexample

    - name: Run tests
      run: |
        cd ammer-core/test
        ./test-hl-linux.sh
        ./test-hlc-linux.sh

  test-java:
    runs-on: ubuntu-latest
    steps:
    - name : Adjust path
      run : |
        if [[ -z "$GITHUB_PATH" ]]; then
            echo "${HOME}/.local/bin" >> $GITHUB_PATH
        fi

    - name: Update apt and install necessary packages
      run : |
        if ! command -v sudo &> /dev/null; then
            apt install sudo
        fi
        sudo apt update
        sudo apt-get install -y software-properties-common

    - name: Install Haxe (4.2.5)
      uses: krdlab/setup-haxe@v1
      with:
        haxe-version: 4.2.5

    - name: Checkout ammer-core
      uses: actions/checkout@v2
      with:
        path: "ammer-core"

    - name: Set up haxelibs
      run: |
        haxelib --quiet install hxjava
        haxelib dev ammer-core ammer-core

    - name: Compile tests
      run: |
        cd ammer-core/test
        haxe -D ammercoretest.java.includepaths="$JAVA_HOME/include:$JAVA_HOME/include/linux" build-java.hxml
        haxe -D ammercoretest.java.includepaths="$JAVA_HOME/include:$JAVA_HOME/include/linux" build-jvm.hxml

    - name: Run tests
      run: |
        cd ammer-core/test
        ./test-java.sh
        ./test-jvm.sh

  test-nodejs:
    runs-on: ubuntu-latest
    steps:
    - name : Adjust path
      run : |
        if [[ ! -z "$GITHUB_PATH" ]]; then
            echo "${HOME}/.local/bin" >> $GITHUB_PATH
        fi

    - name: Update apt and install necessary packages
      run : |
        if ! command -v sudo &> /dev/null; then
            apt install sudo
        fi
        sudo apt update
        sudo apt-get install -y software-properties-common

    - name: Install Haxe (4.2.5)
      uses: krdlab/setup-haxe@v1
      with:
        haxe-version: 4.2.5

    - name: Checkout ammer-core
      uses: actions/checkout@v2
      with:
        path: "ammer-core"

    - name: Set up haxelibs
      run: |
        haxelib --quiet install hxnodejs
        haxelib dev ammer-core ammer-core

    - name: Compile tests
      run: |
        cd ammer-core/test
        haxe build-nodejs.hxml

    - name: Run tests
      run: |
        cd ammer-core/test
        ./test-nodejs.sh

  test-lua:
    runs-on: ubuntu-latest
    steps:
    - name : Adjust path
      run : |
        if [[ ! -z "$GITHUB_PATH" ]]; then
            echo "${HOME}/.local/bin" >> $GITHUB_PATH
        fi

    - name: Update apt and install necessary packages
      run : |
        if ! command -v sudo &> /dev/null; then
            apt install sudo
        fi
        sudo apt update
        sudo apt-get install -y software-properties-common

    - name: Install Haxe (4.2.5)
      uses: krdlab/setup-haxe@v1
      with:
        haxe-version: 4.2.5

    - name: Checkout ammer-core
      uses: actions/checkout@v2
      with:
        path: "ammer-core"

    - name: Set up haxelibs
      run: |
        haxelib dev ammer-core ammer-core

    - name: Install Lua and dependencies
      run: |
        pip3 install hererocks
        hererocks ~/lua5.3 -l5.3 -rlatest --cflags="-fPIC"
        source ~/lua5.3/bin/activate
        ln -s ~/lua5.3/lib/liblua53.a ~/lua5.3/lib/liblua.a
        luarocks install lrexlib-pcre 2.9.1-1
        luarocks install luv 1.41.1-0
        luarocks install luasocket 3.0rc1-2
        luarocks install luautf8 0.1.3-1
        luarocks install bit32 5.3.5.1-1
        luarocks install hx-lua-simdjson 0.0.1-1

    - name: Compile tests
      run: |
        source ~/lua5.3/bin/activate
        cd ammer-core/test
        haxe -D ammercoretest.lua.includepaths=`luarocks config --lua-incdir` -D ammercoretest.lua.librarypaths=`luarocks config --lua-libdir` build-lua.hxml

    - name: Run tests
      run: |
        source ~/lua5.3/bin/activate
        cd ammer-core/test
        ./test-lua-linux.sh
